name: Build Doxygen

on:
# for now, make it manual ??
  push:
    branches: [  ]
#  pull_request:
#    branches: [ master ]

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: ./Doxyfile
        # Working directory
        working-directory: .

    - name: Archive Doxygen pages
      uses: actions/upload-artifact@v1
      with:
        name: makeelf-doxygen
        path: doc/html
