name: Build Doxygen

on:
# for now, make it manual ??
  push:
    branches:
      - master
      - devel
    tags:
      - '*'

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: ./Doxyfile
        # Working directory
        working-directory: .

    - name: Archive Doxygen pages
      uses: actions/upload-artifact@v1
      with:
        name: makeelf-doxygen
        path: doc/html
        
    - name: Upload to webserver
      env:
        DOXYGEN_USER: ${{ secrets.DOXYGEN_USER }}
        DOXYGEN_PASS: ${{ secrets.DOXYGEN_PASS }}
      run: |
        set -e
        cd doc/html
        ls -la
        ftp -i -n static.re-ws.pl <<EOF
        user ${DOXYGEN_USER} ${DOXYGEN_PASS}
        passive
        verbose
        mkdir ${GITHUB_REF##*/}
        cd ${GITHUB_REF##*/}
        mput *
        mkdir search
        mput search/*
        quit
        EOF
